export const products = [
  {
    id: 1,
    name: "Wireless Bluetooth Headphones",
    des: "Noise-canceling over-ear headphones with high-quality sound.",
    price: 79.99,
    category: "Electronics",
    stock: 25,
    rating: 4.5,
    img:
      "https://www.rd.com/wp-content/uploads/2015/12/CalmQuotes-35.jpg?fit=696%2C696",
    tags: ["wireless", "bluetooth", "audio"],
  },
  {
    id: 2,
    name: "Smartphone 12 Pro",
    des: "Latest smartphone with 128GB storage and a stunning camera.",
    price: 999.99,
    category: "Electronics",
    stock: 10,
    rating: 4.8,
    img:
      "https://www.rd.com/wp-content/uploads/2015/12/CalmQuotes-35.jpg?fit=696%2C696",
    tags: ["smartphone", "technology", "mobile"],
  },
  {
    id: 3,
    name: "Men's Running Shoes",
    des: "Lightweight and durable running shoes for all surfaces.",
    price: 49.99,
    category: "Footwear",
    stock: 50,
    rating: 4.3,
    img:
      "https://www.rd.com/wp-content/uploads/2015/12/CalmQuotes-35.jpg?fit=696%2C696",
    tags: ["running", "shoes", "sports"],
  },
  {
    id: 4,
    name: "LED Desk Lamp",
    des: "Adjustable LED lamp with multiple brightness settings.",
    price: 19.99,
    category: "Home & Office",
    stock: 100,
    rating: 4.6,
    img:
      "https://www.rd.com/wp-content/uploads/2015/12/CalmQuotes-35.jpg?fit=696%2C696",
    tags: ["LED", "lamp", "lighting"],
  },
  {
    id: 5,
    name: "Stainless Steel Water Bottle",
    des: "Eco-friendly and BPA-free reusable water bottle.",
    price: 14.99,
    category: "Kitchen & Dining",
    stock: 200,
    rating: 4.7,
    img: "https://example.com/imgs/bottle.jpg",
    tags: ["water bottle", "eco-friendly", "kitchen"],
  },
  {
    id: 6,
    name: "Gaming Keyboard",
    des:
      "Mechanical keyboard with RGB backlighting and programmable keys.",
    price: 89.99,
    category: "Electronics",
    stock: 30,
    rating: 4.8,
    img: "https://example.com/imgs/keyboard.jpg",
    tags: ["keyboard", "gaming", "RGB"],
  },
  {
    id: 7,
    name: "Yoga Mat",
    des: "Non-slip yoga mat with extra cushioning for comfort.",
    price: 24.99,
    category: "Fitness",
    stock: 75,
    rating: 4.5,
    img: "https://example.com/imgs/yoga-mat.jpg",
    tags: ["yoga", "fitness", "mat"],
  },
  {
    id: 8,
    name: "Action Camera",
    des: "Waterproof action camera with 4K video recording capability.",
    price: 149.99,
    category: "Electronics",
    stock: 15,
    rating: 4.7,
    img: "https://example.com/imgs/action-camera.jpg",
    tags: ["camera", "4K", "action"],
  },
  {
    id: 9,
    name: "Electric Kettle",
    des:
      "Fast-boiling electric kettle with 1.7L capacity and auto shut-off.",
    price: 34.99,
    category: "Kitchen & Dining",
    stock: 60,
    rating: 4.6,
    img: "https://example.com/imgs/kettle.jpg",
    tags: ["kettle", "electric", "kitchen"],
  },
  {
    id: 10,
    name: "Portable Power Bank",
    des: "10,000mAh power bank with fast charging support.",
    price: 29.99,
    category: "Electronics",
    stock: 40,
    rating: 4.4,
    img: "https://example.com/imgs/power-bank.jpg",
    tags: ["power bank", "charging", "portable"],
  },
];
