export const products = [
  {
    id: 1,
    name: "Wireless Bluetooth Headphones",
    des: "Noise-canceling over-ear headphones with high-quality sound.",
    price: 79.99,
    category: "Electronics",
    stock: 25,
    rating: 4.5,
    img: "https://media-ik.croma.com/prod/https://media.croma.com/image/upload/v1682587116/Croma%20Assets/Entertainment/Headphones%20and%20Earphones/Images/271047_0_yaama6.png?tr=w-600",
    tags: ["wireless", "bluetooth", "audio"],
  },
  {
    id: 2,
    name: "iphone 16 Pro",
    des: "Latest smartphone with 128GB storage and a stunning camera.",
    price: 999.99,
    category: "Electronics",
    stock: 10,
    rating: 4.8,
    img: "https://www.imagineonline.store/cdn/shop/files/iPhone_16_Pro_Black_Titanium_PDP_Image_Position_1__en-IN_260bf87b-f4aa-451e-95cb-907270ce7696.jpg?v=1727249594",
    tags: ["smartphone", "technology", "mobile"],
  },
  {
    id: 3,
    name: "Men's Running Shoes",
    des: "Lightweight and durable running shoes for all surfaces.",
    price: 49.99,
    category: "Footwear",
    stock: 50,
    rating: 4.3,
    img: "https://static.nike.com/a/images/t_PDP_936_v1/f_auto,q_auto:eco/ca929f7e-f433-46b7-8d83-1a6171c172ce/NIKE+REVOLUTION+7+EASYON.png",
    tags: ["running", "shoes", "sports"],
  },
  {
    id: 4,
    name: "LED Desk Lamp",
    des: "Adjustable LED lamp with multiple brightness settings.",
    price: 19.99,
    category: "Home & Office",
    stock: 100,
    rating: 4.6,
    img: "https://www.auraglow.co.uk/pub/media/catalog/product/cache/c97319a176f100ff38168db5c7f45f43/f/o/folding_desk_lamp002.jpg",
    tags: ["LED", "lamp", "lighting"],
  },
  {
    id: 5,
    name: "Stainless Steel Water Bottle",
    des: "Eco-friendly and BPA-free reusable water bottle.",
    price: 14.99,
    category: "Kitchen & Dining",
    stock: 200,
    rating: 4.7,
    img: "https://fns.co.in/cdn/shop/files/1_18641b2e-f293-4509-8b9b-8d4b52873dc5.jpg?v=1723549064",
    tags: ["water bottle", "eco-friendly", "kitchen"],
  },
  {
    id: 6,
    name: "Gaming Keyboard",
    des: "Mechanical keyboard with RGB backlighting and programmable keys.",
    price: 89.99,
    category: "Electronics",
    stock: 30,
    rating: 4.8,
    img: "https://static1.howtogeekimages.com/wordpress/wp-content/uploads/2022/04/rgb-lit-gaming-mechanical-keyboard.jpg",
    tags: ["keyboard", "gaming", "RGB"],
  },
  {
    id: 7,
    name: "Yoga Mat",
    des: "Non-slip yoga mat with extra cushioning for comfort.",
    price: 24.99,
    category: "Fitness",
    stock: 75,
    rating: 4.5,
    img: "https://5.imimg.com/data5/TestImages/AE/AO/NC/SELLER-11650549/yoga-mat-500x500.png",
    tags: ["yoga", "fitness", "mat"],
  },
  {
    id: 8,
    name: "Action Camera",
    des: "Waterproof action camera with 4K video recording capability.",
    price: 149.99,
    category: "Electronics",
    stock: 15,
    rating: 4.7,
    img: "https://i.pcmag.com/imagery/roundups/03wtEym7INA75ZavVx95FwX-13..v1631714663.jpg",
    tags: ["camera", "4K", "action"],
  },
  {
    id: 9,
    name: "Electric Kettle",
    des: "Fast-boiling electric kettle with 1.7L capacity and auto shut-off.",
    price: 34.99,
    category: "Kitchen & Dining",
    stock: 60,
    rating: 4.6,
    img: "https://www.vidiem.in/uploads/images/Kettle_Chrome_r1.png",
    tags: ["kettle", "electric", "kitchen"],
  },
  {
    id: 10,
    name: "Portable Power Bank",
    des: "10,000mAh power bank with fast charging support.",
    price: 29.99,
    category: "Electronics",
    stock: 40,
    rating: 4.4,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfJC56Xv5sJZ0Tj5kHHjKGnWJVHZ-Ffz0RXQ&s",
    tags: ["power bank", "charging", "portable"],
  },
  {
    id: 11,
    name: "LED Desk Lamp",
    des: "Adjustable LED lamp with multiple brightness settings.",
    price: 19.99,
    category: "Home & Office",
    stock: 100,
    rating: 4.6,
    img: "https://m.media-amazon.com/images/I/61QPRxJk3dL.jpg",
    tags: ["LED", "lamp", "lighting"],
  },
  {
    id: 12,
    name: "Wireless Bluetooth Headphones",
    des: "Noise-canceling over-ear headphones with high-quality sound.",
    price: 79.99,
    category: "Electronics",
    stock: 25,
    rating: 4.5,
    img: "https://m.media-amazon.com/images/I/61Gzf69kVPL._AC_UF1000,1000_QL80_.jpg",
    tags: ["wireless", "bluetooth", "audio"],
  },
];
